version: '3.8'

services:
  app:
    build: .
    container_name: sb-neo4j-app
    ports:
      - 8080:8080
    environment:
      - SPRING_NEO4J_URI=bolt://db:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
      - SPRING_DATA_NEO4J_DATABASE=neo4j

  db:
    image: neo4j
    container_name: sb-neo4j-db
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1" ]
      interval: 10s
      timeout: 5s
      retries: 5